version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --save "900 1"
      --save "300 10"
      --save "60 1000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_BROKER_ID: 1
    volumes:
      - ./kafka-data:/bitnami/kafka
  ghost-primary-backend:
    build: ./ghost-primary-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - kafka
      - minio
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
      KAFKA_BROKER: kafka:9092

  ghost-message-service:
    build: ./ghost-message-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092

  ghost-message-worker:
    build: ./ghost-message-worker
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ghostdbb:/var/lib/postgresql/data

volumes:
  ghostdbb:
